### ISSUE TITLE
Method genRemoteOp in Class RemoteOp: I am confused by the dpid numbering

### ISSUE THREAD

**Issue by nancy0361** [shado-av/shado-server#1]
I thought the dpid is two digits now (e.g. 00, 01, 02), but in line 82 it says dpid is (i * 100 + j) which is 3 digits. Can you explain more on it?

link to code: [https://github.com/shado-av/shado-server/blob/master/core/server/src/main/java/server/Engine/RemoteOp.java](url)

**Comment by nancy0361** [comment]
And also I don't understand in the line 78 why i is looping over the number of tasks. I thought it should be the number of teams.

**Comment by FishMage** [comment]
Hi Naixin, I'm still modifying this part. Victoria said the simulation should allow 100+ team/vehicles so I change 10 to 100 but I haven't done all changes yet.
For another question, yes you are right the outer loop should be numTeams. I've already changed this part a few days ago. You can pull the latest change with the modified version of queueing module.
