### ISSUE TITLE
SHADO parameter test failed

### ISSUE THREAD

**Issue by nancy0361** [shado-av/shado-server#2]
This could be my problem. 

I tried to used the [http://apps.hal.pratt.duke.edu/shado-web-simple/index.html](url) test website to test the server and it failed to give me the result. It at first said the path was not correct. I changed the path (on branch naixin_test, I didn't touch the master branch), pushed and pulled again, then it complained that the parameter was not correct.

This could either be I gave the wrong parameter or some bugs in the code. I am trying to figure it out. The parameter I was using looked like this:
![screen shot 2018-05-12 at 11 05 17 am](https://user-images.githubusercontent.com/35504511/39961310-33b7133e-5601-11e8-9358-09922cbc5517.png)

And this:
![screen shot 2018-05-12 at 4 25 25 pm](https://user-images.githubusercontent.com/35504511/39961314-4a7c4b20-5601-11e8-84db-107d0a24e47e.png)
![screen shot 2018-05-12 at 4 25 33 pm](https://user-images.githubusercontent.com/35504511/39961316-4d446004-5601-11e8-87ef-eb8612eabc16.png)

**Comment by FishMage** [comment]
For the first simulation, it fails because the number of tasks didn't match. Fleet can generate task [0,1,2] but there is only 1 task specified in the task section so it will cause an IndexOutOfBound Execption.

The error in the second simulation might be the parameter in the Human Error Probability. It takes 3 parameters but you only have 2.

**Comment by nancy0361** [comment]
I changed the parameters as you said, but still get the same error. Here is what I used:
![screen shot 2018-05-15 at 12 58 07 pm](https://user-images.githubusercontent.com/35504511/40071790-d2c65710-583f-11e8-9cdc-b83531c121a5.png)
![screen shot 2018-05-15 at 12 58 23 pm](https://user-images.githubusercontent.com/35504511/40071796-d7533384-583f-11e8-8ca2-8c2b28be405b.png)

**Comment by nancy0361** [comment]
Do you mind give me an example input, like a JSON file, that you know it can work? I think it will help a lot. And also do I need to git pull and run the server again?

**Comment by FishMage** [comment]
{"numHours":8,"traffic":[0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5],"numReps":10,"numRemoteOp":4,"numTeams":1,"numvehicles":[1],"autolvl":1,"numPhases":2,"hasExogenous":[0,0],"exNames":[],"exTypes":[],"failThreshold":0.5,
"opStrats":"N","opNames":["Dispatcher"],"opTasks":[[0,1,2,3,4,5,6]],"teamComm":["N"],"teamSize":[4],"fleetTypes":1,"fleetHetero":[[0,1,2,3,4,5,6]],"numTaskTypes":7,"taskNames":["Actuation","DM","DC1","DC2","Comms_Other","Record Keeping"," Referencing"],"taskPrty":[[4,7],[5,5],[2,5],[5,3],[3,4],[3,2],[3,4]],"arrDists":["E","E","E","E","E","E","E"],"arrPms":[[0.2,0.2],[0.2,0.2],[0.01006,0.01006],[0.01006,0.01006],[0.57,0.57],[0.899,0.899],[0.899,0.899]],"serDists":["U","U","U","U","E","U","U"],"serPms":[[0.5,2],[0,0.5],[0.167,2.5],[0.167,2.5],[0.133,0.133],[0.05,1.5],[0.05,1.5]],"expDists":["E","E","E","E","E","E","E"],"expPmsLo":[[0,0.184],[0,0.184],[0,0.184],[0,0.184],[0,0.184],[0,0.184],[0,0.184]],"expPmsHi":[[0,0.184],[0,0.184],[0,0.184],[0,0.184],[0,0.184],[0,0.184],[0,0.184]],"affByTraff":[[0,1],[0,1],[0,1],[0,1],[0,1],[0,1],[0,1]],"teamCoordAff":["0","1","0","0","1","0","1"],"humanError":[[0.003,0.00008,0.007],[0.003,0.00008,0.007],[0.003,0.00008,0.007],[0.003,0.00008,0.007],[0.003,0.00008,0.007],[0.003,0.00008,0.007],[0.003,0.00008,0.007]]}

**Comment by FishMage** [comment]
I can't see any error in the simulation page you posted. What's the error message the server retruns? Did you deployed another version of SHADO-server instance to the server? Try to make sure the server is working.
For the VehicleID, I think it won't influence the simulation results. I changed it to 0 temporarily but It should be the real vehicleID.

**Comment by nancy0361** [comment]
I tried your JSON file. It works!

**Comment by FishMage** [comment]
I ran the simulation on my phone and I got the JavaNoClassDef Exception. Did you update the jar on the server?

**Comment by nancy0361** [comment]
Yes, I did. But I just pulled the master and run. I might changed the directory. I will check it. The master branch can work without any change right?

**Comment by nancy0361** [comment]
Everything works fine now. I will close this issue.
